homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include customized.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  login_attempts_threshold: 3

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

###  Automation  ###
automation: !include_dir_merge_list automation

###  Groups  ###
group: !include_dir_merge_named groups

zone:
  name: Work (Stephanie)
  latitude: !secret work_steph_latitude
  longitude: !secret work_steph_longitude
  radius: 75
  icon: mdi:domain

zone 2:
  name: Work (John Paul)
  latitude: !secret work_jp_latitude
  longitude: !secret work_jp_longitude
  radius: 325 
  icon: mdi:domain

# This will override the default home zone
zone 3:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: 100
  icon: mdi:home

# Track the sun
sun:

# Track the moon
sensor:
  platform: moon

# Weather Prediction
sensor:
  platform: darksky
  api_key: !secret darksky_api_key
  forecase: 7
  monitored_conditions:
    - summary
    - hourly_summary
    - temperature
    - apparent_temperature
    - humidity
    - wind_speed
    - precip_type
    - precip_intensity
    - precip_probability

# Text to speech
tts:
  platform: google

emulated_hue:
  host_ip: 192.168.2.82
  listen_port: 8300
  expose_by_default: false
  exposed_domains:
    - light
    - switch
    - group

zwave:
  usb_path: /dev/ttyACM0

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

device_tracker owntracks:
  platform: owntracks

light:
  - platform: lifx
    broadcast: 192.168.2.255
  - platform: limitlessled
    bridges:
      - host: 192.168.1.136
        groups:
          - number: 1
            name: led_strip_rgb_cct_1
            type: rgbww
            fade: on

media_player:
  - platform: denon
    host: 192.168.1.131

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

